on:
  push:
    branches:
      - main
    tags:
      - '**'
  workflow_dispatch:
  pull_request:

name: CI

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
      - uses: cachix/cachix-action@v15
        with:
          name: newam
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check -L

  release:
    name: crates.io release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Publish
        run: cargo publish --no-verify --token ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
